# Generated by Django 4.0.4 on 2022-05-24 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_num', models.DecimalField(decimal_places=1, max_digits=10)),
                ('name', models.CharField(max_length=50)),
                ('college', models.CharField(max_length=30)),
                ('major', models.CharField(max_length=30)),
                ('student_type', models.CharField(choices=[('UNDERGRADUATE', 'Undergraduate'), ('GRADUATE', 'Graduate'), ('EXCHANGE', 'Exchange')], max_length=20)),
                ('entrance_date', models.DateField()),
            ],
        ),
    ]
