# Generated by Django 4.0.4 on 2022-05-24 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_num',
            field=models.IntegerField(max_length=10),
        ),
    ]
