# Generated by Django 4.0.4 on 2022-05-24 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_student_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_num',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
